# Generated by Django 4.1.4 on 2022-12-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=150)),
                ("description", models.TextField(default="")),
                ("country", models.CharField(default="", max_length=150)),
                ("type_beer", models.CharField(default="", max_length=150)),
                ("company", models.CharField(default="", max_length=150)),
                ("colour", models.CharField(default="", max_length=150)),
                ("graduation", models.FloatField(default=0.0)),
                ("size", models.FloatField(default=0.0)),
                ("price", models.FloatField(default=0.0)),
                ("photo_link", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
