# Generated by Django 4.1.4 on 2023-01-03 16:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("BeerApp", "0003_rename_beerliked_likedbeer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="likedbeer",
            unique_together={("user", "beer")},
        ),
    ]
